---
title: "Lab 03 - Nobel laureates"
author: "Qilin"
date: "1/14/2023"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
```

## Exercises

### Exercise 1
```{r dimension}
dim(nobel)
#for getting the number of observations and variables
print(nobel)
#for understanding what each row represent
```
935 observations and 26 variables
Each row represents a single observation

### Exercise 2
```{r nobel_living}
nobel_living <- nobel %>%
  filter(!is.na(country), gender != "org", is.na(died_date))
```

### Exercise 3
```{r nobel_living_science}
nobel_living <- nobel_living %>%
  mutate(
    country_us = if_else(
      country == "USA", "USA", "Other"
    )
  )

nobel_living_science <- nobel_living %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))

```


### Exercise 4
```{r faceted_bar_plot}

ggplot(nobel_living_science, mapping = aes(y= country_us, fill = category))+
  geom_bar(position = "dodge")


```

...

### Exercise 5

...

### Exercise 6

...
